language: php

php:
  - '7.2'
  - '7.3'

addons:
  mariadb: '10.3'

sudo: false

before_script:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- cp .env.testing .env
- composer install --prefer-source --no-interaction
- php artisan key:generate

before_install:
- mysql -e 'CREATE DATABASE indiehd_test;'
- mysql -e "CREATE USER 'homestead'@'%' IDENTIFIED BY 'secret';"
- mysql --user=root -e "GRANT ALL PRIVILEGES ON indiehd_test.* TO 'homestead'@'%' WITH GRANT OPTION;"
- mysql --user=root -e 'FLUSH PRIVILEGES;'

services:
- mysql

script:
  - mkdir -p build/logs
  - phpdbg -qrr vendor/bin/phpunit tests --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -vvv
  - ./send.sh success $DISCORD_WEBHOOK

after_failure:
  - ./send.sh failure $DISCORD_WEBHOOK

notifications:
  email:
#    recipients:
#      - gtaylor@electricwerks.com
#    on_success: always
#    on_failure: always
    on_failure: change
